### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by madAndroid** [raphink/mspectator#3]
Hi, this looks great - have been meaning to implement something along these lines; however, one of the dependencies appears to have changed - puppet-spec has become puppet-policy? there seems to be a redirect on that repo. Is it still possible to follow the steps in the mspectator README.md, even though the dependency has changed?

If it's not still active / in use - is there an alternative you can recommend?

Thanks in advance! :)

**Comment by raphink** [comment]
Hi,

I'm not actively using mspectator in production, and I don't know anyone else that does. That said, the code did work last time I used it (which is where I gave a talk on it for Puppetconf 2014). If there's adjustments to be made (yes, puppet-spec was renamed to puppet-policy some time after Puppetconf), I certainly welcome feedback and PRs!

And no, I don't know any alternative to that. In fact, the [talk at Puppetconf](http://www.slideshare.net/PuppetLabs/puppetconf-mspectator-talk) might shed a light on what led to writing this software.

**Comment by beddari** [comment]
We tested it when @raphink first published it with good results! But then over time we could not build enough confidence around getting ActiveMQ running properly and reliably. We're now using a similar workflow largely inspired by this using Consul and some unpublished "private glue".

**Comment by madAndroid** [comment]
Oh awesome - yes, we've been using Consul as well, given that MCollective can be a bit flakey.. but there's very little in the way of a plugin infrastructure atm, from what we've seen. Any plans to open source your "private glue" ?

**Comment by beddari** [comment]
Yes, plans exist when it is less crude and more useful :-) We're building ontop of http://python-consul.readthedocs.org/en/latest/ ...
